name: tests


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:latest
      options: --user root
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: install setup
        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          python3 -m pip install --upgrade pip
          pip3 install    .
          make test
